[changelog]
header = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}\n
{% for commit in commits %}
- {{ commit.message | upper_first }}\n
{% endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
    { message = "^feat", group = "Features"},
    { message = "^fix", group = "Bug Fixes"},
    { message = "^docs", group = "Documentation"},
    { message = "^refactor", group = "Refactoring"},
    { message = "^test", group = "Testing"},
    { message = "^chore", group = "Miscellaneous Tasks"},
]
skip_tags = "v0.1.0-beta.1"
